import { Player, BoardCell } from "./types";

export const players: Player[] = [
  {
    id: "player1",
    name: "Max",
    icon: "🫅",
    color: "gold",
    position: 0,
    money: 20,
    properties: {},
  },
  {
    id: "player2",
    name: "Romka",
    icon: "🧔",
    color: "lightblue",
    position: 0,
    money: 20,
    properties: {},
  },
];

export const cells: Array<BoardCell> = [
  {
    id: "start",
    type: "special",
    className: "start",
    label: "Start",
    icon: "⬅️",
  },
  {
    id: "dog",
    type: "property",
    className: "bottom1",
    label: "Dog",
    icon: "🐶",
    color: "brown",
    price: 1,
  },
  {
    id: "cat",
    type: "property",

    className: "bottom2",
    label: "Cat",
    icon: "🐱",
    color: "brown",
    price: 1,
  },
  {
    id: "chance1",
    type: "special",
    className: "bottom3",
    label: "Village vacation",
    icon: "❓️",
  },
  {
    id: "strawberry",
    type: "property",
    className: "bottom4",
    label: "Strawberry",
    icon: "🍓",
    color: "lightblue",
    price: 1,
  },
  {
    id: "raspberry",
    type: "property",
    className: "bottom5",
    label: "Raspberry",
    icon: "🫐", // no raspberry unicode emoji, using blueberry as a placeholder
    color: "lightblue",
    price: 1,
  },
  { id: "jail", type: "special", label: "Jail", className: "jail", icon: "⛓️" },
  {
    id: "chicken",
    type: "property",
    className: "left1",
    label: "Chicken",
    icon: "🐔",
    color: "purple",
    price: 2,
  },
  {
    id: "bee",
    type: "property",
    className: "left2",
    label: "Bee",
    icon: "🐝",
    color: "purple",
    price: 2,
  },
  {
    id: "chance2",
    type: "special",
    className: "left3",
    label: "Village vacation",
    icon: "❓️",
  },
  {
    id: "watermill",
    type: "property",
    className: "left4",
    label: "Watermill",
    icon: "🛞",
    color: "orange",
    textColor: "black",
    price: 2,
  },
  {
    id: "corn",
    type: "property",
    className: "left5",
    label: "Corn",
    icon: "🌽",
    color: "orange",
    textColor: "black",
    price: 2,
  },
  {
    id: "parking",
    type: "special",
    className: "parking",
    label: "Parking",
    icon: "🅿️",
  },
  {
    id: "apple",
    type: "property",
    className: "top1",
    label: "Apple",
    icon: "🍎",
    color: "red",
    price: 3,
  },
  {
    id: "carrot",
    type: "property",
    className: "top2",
    label: "Carrot",
    icon: "🥕",
    color: "red",
    price: 3,
  },
  {
    id: "chance3",
    type: "special",
    className: "top3",
    label: "Village vacation",
    icon: "❓️",
  },
  {
    id: "horse",
    type: "property",
    className: "top4",
    label: "Horse",
    icon: "🐴",
    color: "lightgreen",
    price: 3,
  },
  {
    id: "pig",
    type: "property",
    className: "top5",
    label: "Pig",
    icon: "🐷",
    color: "lightgreen",
    price: 3,
  },
  {
    id: "police",
    type: "special",
    label: "Police",
    className: "police",
    icon: "👮‍♂️",
  },
  {
    id: "tractor",
    type: "property",
    className: "right1",
    label: "Tractor",
    icon: "🚜",
    color: "darkgreen",
    price: 4,
  },
  {
    id: "cow",
    type: "property",
    className: "right2",
    label: "Cow",
    icon: "🐮",
    color: "darkgreen",
    price: 4,
  },
  {
    id: "chance4",
    type: "special",
    className: "right3",
    label: "Village vacation",
    icon: "❓️",
  },
  {
    id: "market",
    type: "property",
    className: "right4",
    label: "Market",
    icon: "🏪",
    color: "darkblue",
    price: 5,
  },
  {
    id: "farm",
    type: "property",
    className: "right5",
    label: "Farm",
    icon: "👨‍🌾",
    color: "darkblue",
    price: 5,
  },
];
